# This is a basic workflow to help you get started with Actions

name: Hello

on:
    push:
        branches:
        - main

jobs:
    hello:
        runs-on: ubuntu-latest
        steps:
          - name: Say Hello
            run: echo "hello, world!"
